---
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.4.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-angular"]
        args: ["--config", "./commitlint.config.js"]
